// File generated by FlutterFire CLI & customized for Ev Asistanı.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web platformu için Firebase seçenekleri.
  ///
  /// GERÇEK PROJE BAĞLANTISI: Firebase Console -> Project Settings -> General -> Web App
  /// adımlarından aldığınız apiKey, appId, messagingSenderId, projectId vb. değerlerini
  /// buradaki alanlara yapıştırarak canlı Firebase projenizi kolayca bağlayabilirsiniz.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAcmAOwqjWc0RbVczTWJerFb21WgpqFoA',
    appId: '1:687057369612:web:1bff23ddf99ada4ef30c29',
    messagingSenderId: '687057369612',
    projectId: 'ev-asistani-1',
    authDomain: 'ev-asistani-1.firebaseapp.com',
    storageBucket: 'ev-asistani-1.firebasestorage.app',
    measurementId: 'G-FDB4E7L4RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNwdpCdvovZ__2EisBqBNty__P-1kfIus',
    appId: '1:687057369612:android:9a761ba69e159258f30c29',
    messagingSenderId: '687057369612',
    projectId: 'ev-asistani-1',
    storageBucket: 'ev-asistani-1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsL4mXwvhLlkbjqpOYdS70MLmZ89WT23g',
    appId: '1:687057369612:ios:52db05bea7d40ddbf30c29',
    messagingSenderId: '687057369612',
    projectId: 'ev-asistani-1',
    storageBucket: 'ev-asistani-1.firebasestorage.app',
    iosClientId: '687057369612-4bljhci5up2bnaqdmmf5b2tq9p1o4or9.apps.googleusercontent.com',
    iosBundleId: 'com.evasisstani.evAsistani',
  );
}
